env:
  global:
  - secure: QhRqwg5mc3Wv74JybkNzzAcvZnz/Tir02y/NdFCPOXy6t5Qx53m5HPgpdJGfT7xl1vTpRwa+/OTCDSWF7lxPPm/TcXCzHaxNDPGxjXRknvaYdHTzTydur0r4fpaI2WlgynlfxbS2RqTh3MA2V5CVbtKSZuGsfxwRUcuCPpoJUKYeCsqiWpAvs80MXexsrAT6gDNtlm7DB9HxRcv07Y2zSz0kNjJpRfgjpcqbG+lQRt0SMFJ9Iy7ecW7dnrsHKXyGk+L3Xh4mNr/czFitGc8WfxJyzViNl4CjNMMqLKvSPlJu79Le5WZ4rUaEyc12K1H9TmOP9drbxzTIIYhpkeZ9VaojZ4O3BVGT3cnEmyXA6InGzmfvVyasVJPZb5WBsRozEmUR0NcPeOTRes0aJNdfiNG+5O4RhD+zRhLN+5l8C1bR38r63zFFdXBf3NgT/C7C3gakxfaF66hE4mHeFIWKeFKjXgjsJ1UtUNcB4vl6wVbEI9BexKRHDiTIuV/GFpk4XRMCw75FyMF1LMh75k9Q7SJ6+SX/N5nPSf5CeU1R8FEdclat/NgsYX5HUhwDKjxVUHR/FWX+JKbfX4ela7UbSt3zKy3yq6U2VrWPlaBwq8NYzWu3ee07qPgycizLfY/maD/eydL9QB0gERVD9g1FrQ0MljAj6C3byXv1aYErHho=
language: node_js
node_js:
- '11'
jobs:
  include:
  - stage: Installing dependencies
    script: yarn install
  - stage: Unit test
    script: yarn test:prod
  - stage: Deploy
    if: branch = master
    script:
      - npm install -g firebase-tools
      - yarn build
      - firebase deploy --token $global